apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    project: expense
    tier: web
    component: frontend
  namespace: expense
spec:
  replicas: 2
  selector:
    matchLabels:
      project: expense
      tier: web
      component: frontend
  template:
    metadata:
      labels:
        project: expense
        tier: web
        component: frontend
    spec:
      containers:
      - name: frontend
        imagePullPolicy: Always
        image: gopi1998/frontend:{{ .Values.Deployment.imageVersion }} #will replace with our frontend image
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "100m"
            memory: "128Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          failureThreshold: 2
          periodSeconds: 5
          initialDelaySeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          failureThreshold: 2
          periodSeconds: 5
          initialDelaySeconds: 30
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
          readOnly: true
      volumes:
      - name: nginx-config
        configMap:
          name: frontend
          items:
          - key: nginx.conf
            path: nginx.conf
